name: Movie Picture Backend Continuous Integration

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:
      
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v4
        with:
          python-version: 3.11

      - run: cd starter/backend && pipenv install

      # Run the linter.
      - run: cd starter/backend && pipenv run lint

  test:

    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v4
        with:
          python-version: 3.11

      - run: cd starter/backend && pipenv install

      # Run the tests
      - run: cd starter/backend && pipenv run test

  build:
  #job should only run after the first 2 succeed
    runs-on: ubuntu-latest
  
    needs: [lint, test]

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: cd starter/frontend && pipenv install

      - name: Build Docker Image
        run: |
        docker build -t mp-backend:latest .